app/views/comment.py
from flask import (Blueprint, url_for, render_template, session,
                   request, redirect, g, jsonify, flash, make_response,
                   current_app)

from ..decorators import login_required
from ..models.user import User
from ..models.comment import Comment

from app import api

mod = Blueprint('comment', __name__, url_prefix='/comment')


@mod.route('/<int:comment_id>/delete', methods=['DELETE', 'POST'])
@login_required
def delete_comment(comment_id):

    origin_post = api.delete_post_comment(comment_id)

    flash('Comment deleted successfully', category='success')
    return redirect(url_for('post.view_post', post_id=origin_post))


@mod.route('/<int:comment_id>/edit', methods=['POST'])
@login_required
def edit_comment(comment_id):
    updated_comment = request.form['new_comment']
    api.edit_comment(comment_id, updated_comment)

    resp = jsonify(message='ok')
    resp.status_code = 200
    return resp


@mod.route('/<int:comment_id>/', methods=['GET'])
def view_comment(comment_id):
    perma_comment = api.get_single_comment(comment_id)
    post = api.get_single_post(via_comment=perma_comment)
    #get context for comment
    context_tree = api.get_post_comments(post[0], context_id=perma_comment.key.id())

    return render_template("post.html", content=post, comments=context_tree)


@mod.route('/_newest', methods=['GET'])
def latest_comment():
    user = g.user
    comment = Comment.query().filter(Comment.author == user.key).order(-Comment.date_created).get()
    comment.depth = 0
    comment.children = []

    render_comment = get_macro_with_context('/macros/_render_comments.html', 'render_comments')
    latest_comment = render_comment([comment])
    resp = make_response(latest_comment)
    return resp


def get_macro_with_context(template_name, macro_name):
    template = current_app.jinja_env.get_template(template_name)
    module = template.make_module({'session': session, 'g': g})
    macro = getattr(module, macro_name)
    return macro

app/templates/macros/_render_comments.html
{% macro render_comments(comments) %}

    {% for comment in comments %}
    <div class="comment" style="margin-left:{{ comment.depth*3}}%">
        {% if not comment.deleted %}
            <div class="c_votes">
                <a href="/comment/"><i class="icon-chevron-up up" data-id="{{ comment.key.id() }}" style="display: {{ none if dir == '1'}}"></i></a>
                <a href="/comment/"><i class="icon-chevron-down down" data-id="{{ comment.key.id() }}" style="display: {{ none if dir == '-1' }}"></i></a>
            </div>
        {% endif %}
        <span class="comment_info">
            {% if comment.deleted %}
                <span style="margin-rigt:.5%"> Comment removed </span>
            {% else %}
                <a style="margin-right:.5%;"> {{ comment.author.get().username }} </a> {{ "  0 Points" if not comment.votes else comment.votes }} {{ comment.ago }} | <a href="{{ url_for('comment.view_comment', comment_id=comment.key.id()) }}"> link </a>
            {% endif %}
        </span>
        {% if not comment.deleted %}
            <p class="c_body"> {{ comment.comment_text }} </p>
            {% if session.get('username') is not none %}
                <button class="btn btn-mini reply" type="button">Reply</button>
            {% endif %}

            {% if g.user == comment.author.get() %}
            <button class="btn btn-mini edit" type="button">Edit</button>
            <form method="POST" action="{{ url_for('comment.delete_comment', comment_id= comment.key.id()) }}" style="display: inline">
            <button class="btn btn-mini delete" type="submit">Delete</button>
            </form>
            {% endif %}
        {% endif %}
    </div>

    {% for child in comment.children %}
        {{ render_comments([child]) }}
    {% endfor %}
    
    {% endfor %}

{% endmacro %}

app/templates/macros/_render_post.html
{% macro render_post(post, i, voters, page_num, last=false,comments=none) %}
{% if g.user %}
    {% if g.user.key in voters %}
        {% set dir = post.voters[voters.index(g.user.key)].direction %}
    {% endif %}
{% endif %}

    <div class="link">
        {% if i %}
        <span class="badge badge-info">{{ i + (page_num * 10) }}</span>
        {% endif %}
        <button class="btn pts" type="button disabled" disabled="disabled">{{ post.votes }} Points</button>
        <div class="votes">
            <a href="/post/"><i class="icon-chevron-up up" data-id="{{ post.key.id() }}" style="display: {{ none if dir == '1'}}"></i></a>
            <a href="/post/"><i class="icon-chevron-down down" data-id="{{ post.key.id() }}" style="display: {{ none if dir == '-1' }}"></i></a>
        </div>
        <span class="headline">
            <a href="{{ post.link }}">{{ post.title }}</a>
            ({{ post.link.split('/')[2].lstrip('www.') if post.link.startswith(('http://','https://')) else post.link }})
        </span>
        <span class="stats">
            Posted by <a href=#>{{ post.author.get().username }}</a> {{ post.ago }}
            <a href="{{ url_for('post.view_post', post_id=post.key.id()) }}">{{ "discus this" if post.num_comments is none else post.num_comments ~ " Comments"}}</a>

        </span>
    </div>

    {% if comments is not none %}
    {% from 'macros/_render_comments.html' import render_comments with context %}
    <form method="POST" action="/post/{{ post.key.id() }}/addcomment">
        <textarea name="comment" style="width: 450px; height: 50px; position: relative; left: 2%;"></textarea>
        <button type="submit" class="btn" style="display: block; margin-left: 14px;">Add Comment</button>
    </form>
    {{ render_comments(comments) }}
    {% endif %}

    {% if last %}
    <span id="cur_info" style="display: none;" data-cur_string="{{ cur_string }}" data-page_num="{{ page_num }}" data-more_content="{{ more }}"></span>
    {% endif %}

{% endmacro %}