app/models/comment.py
from google.appengine.ext import ndb

from .user import User
from .post import Post


from ..helpers import time_ago


class Comment(ndb.Model):
    comment_text = ndb.TextProperty(indexed=True)
    date_created = ndb.DateTimeProperty(auto_now_add=True)
    author = ndb.KeyProperty(kind=User)
    post = ndb.KeyProperty(kind=Post)
    votes = ndb.IntegerProperty()
    parent = ndb.KeyProperty(kind='Comment')
    ago = ndb.ComputedProperty(lambda self: time_ago(self.date_created))
    deleted = ndb.BooleanProperty()

    def add(self, text, author, post, parent=None):
        self.comment_text = text
        self.author = author
        self.post = post
        self.parent = parent
        self.votes = 0
        self.deleted = False
        self.put()

    def partial_delete(self):
        self.deleted = True
        self.comment_text = ""
        self.votes = 0
        self.put()

app/models/post.py
from google.appengine.ext import ndb
from .user import User
from math import log
from datetime import datetime, timedelta
from ..helpers import time_ago


class Voter(ndb.Model):
    voter_id = ndb.KeyProperty(kind=User)
    direction = ndb.StringProperty()


class Post(ndb.Model):
    votes = ndb.IntegerProperty()
    date_created = ndb.DateTimeProperty(auto_now_add=True)
    num_comments = ndb.IntegerProperty()
    hot_score = ndb.ComputedProperty(lambda self: hotness(self.date_created, self.votes), indexed=True)
    ago = ndb.ComputedProperty(lambda self: time_ago(self.date_created))
    title = ndb.StringProperty()
    description = ndb.TextProperty()
    link = ndb.StringProperty()
    author = ndb.KeyProperty(kind=User)
    voters = ndb.StructuredProperty(Voter, repeated=True)

    def add(self, title, link, desc, key):
        self.title = title
        self.link = link
        self.description = desc
        self.author = key
        self.votes = 0
        self.put()

    def get_comment_tree(self, single_root_id=None):
        from .comment import Comment

        def make_comment_tree(base_comment, depth=1):
            siblings = Comment.query() \
                              .filter(Comment.parent == base_comment.key) \
                              .order(-Comment.votes) \
                              .fetch()
            base_comment.children = []
            base_comment.depth = depth - 1
            for comment in siblings:
                comment.depth = depth + 1
                base_comment.children.append(comment)
                make_comment_tree(comment, depth=depth + 1)

            return base_comment

        if single_root_id is not None:
            root_comments = [Comment.get_by_id(single_root_id)]
        else:
            root_comments = Comment.query() \
                                   .filter(Comment.post == self.key) \
                                   .filter(Comment.parent == None) \
                                   .order(-Comment.votes) \
                                   .fetch()

        comment_tree = [make_comment_tree(root)
                        for root in root_comments]

        return comment_tree


def hotness(date, score):

    if date is None:
        return

    def epoch_seconds(date):

        epoch = datetime(1970, 1, 1)
        td = date - epoch

        return td.days * 86400 + td.seconds + (float(td.microseconds) / 1000000)

    order = log(max(abs(score), 1), 10)
    sign = 1 if score > 0 else -1 if score < 0 else 0
    seconds = epoch_seconds(date) - 1134028003

    return round(order + sign * seconds / 45000, 7)

app/views/account.py
from flask import (Blueprint, url_for, render_template,
                   request, redirect, session, jsonify,
                   flash)

from ..models.user import User

from pybcrypt import bcrypt

mod = Blueprint('account', __name__)


@mod.route('/login', methods=['GET', 'POST'])
def login():
    error = False
    next_url = request.args.get('after') if request.args.get('after') is not None else url_for('frontend.index')

    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        user = User.query(User.username == username).get()
        if user is not None and bcrypt.hashpw(password, user.pwhash) == user.pwhash:
            session['username'] = username
            next_url = request.args.get('after')
            flash('Successfully logged in!', category='success')
            return redirect(next_url)
        else:
            error = True

    return render_template('login.html', error=error, next_url=next_url)


@mod.route('/register', methods=['GET', 'POST'])
def register():

    if request.method == 'POST':
        username = request.form['username']
        password = request.form['password']
        pwhash = bcrypt.hashpw(password, bcrypt.gensalt())
        u = User()
        u.register(username, pwhash)
        session['username'] = username
        return redirect(url_for('frontend.index'))

    else:
        return render_template('register.html')


@mod.route('/logout')
def logout():
    session.pop('username', None)
    flash('Logged out successfully', category='success')
    return redirect(url_for('frontend.index'))


@mod.route('/_check_username')
def check_username():
    pending_username = request.args.get('username')
    is_taken = User.query(User.username == pending_username).get()

    if is_taken is None:
        response = "all good"
    else:
        response = "taken"

    return jsonify(result=response)

app/views/comment.py
from flask import (Blueprint, url_for, render_template, session,
                   request, redirect, g, jsonify, flash, make_response,
                   current_app)

from ..decorators import login_required
from ..models.user import User
from ..models.comment import Comment

from app import api

mod = Blueprint('comment', __name__, url_prefix='/comment')


@mod.route('/<int:comment_id>/delete', methods=['DELETE', 'POST'])
@login_required
def delete_comment(comment_id):

    origin_post = api.delete_post_comment(comment_id)

    flash('Comment deleted successfully', category='success')
    return redirect(url_for('post.view_post', post_id=origin_post))


@mod.route('/<int:comment_id>/edit', methods=['POST'])
@login_required
def edit_comment(comment_id):
    updated_comment = request.form['new_comment']
    api.edit_comment(comment_id, updated_comment)

    resp = jsonify(message='ok')
    resp.status_code = 200
    return resp


@mod.route('/<int:comment_id>/', methods=['GET'])
def view_comment(comment_id):
    perma_comment = api.get_single_comment(comment_id)
    post = api.get_single_post(via_comment=perma_comment)
    #get context for comment
    context_tree = api.get_post_comments(post[0], context_id=perma_comment.key.id())

    return render_template("post.html", content=post, comments=context_tree)


@mod.route('/_newest', methods=['GET'])
def latest_comment():
    user = g.user
    comment = Comment.query().filter(Comment.author == user.key).order(-Comment.date_created).get()
    comment.depth = 0
    comment.children = []

    render_comment = get_macro_with_context('/macros/_render_comments.html', 'render_comments')
    latest_comment = render_comment([comment])
    resp = make_response(latest_comment)
    return resp


def get_macro_with_context(template_name, macro_name):
    template = current_app.jinja_env.get_template(template_name)
    module = template.make_module({'session': session, 'g': g})
    macro = getattr(module, macro_name)
    return macro

app/views/post.py
from flask import (Blueprint, url_for, render_template, session,
                   request, redirect, g, jsonify, flash)

from ..models.user import User
from ..models.post import Post, Voter
from ..decorators import login_required

from app import api

mod = Blueprint('post', __name__, url_prefix='/post')


@mod.route('/<int:post_id>/', methods=['GET'])
def view_post(post_id):
    post = api.get_single_post(post_id)
    comments = api.get_post_comments(post[0])

    return render_template('post.html', content=post, comments=comments)


@mod.route("/<int:post_id>/addcomment", methods=['GET', 'POST'])
@mod.route("/<int:post_id>/<int:parent_id>/reply", methods=['GET', 'POST'])
@login_required
def add_comment(post_id, parent_id=None):

    if request.method == 'POST':
        comment_text = request.form['comment']
        if comment_text:
            flash('Comment added successfully', category='success')
            api.add_comment(post_id, comment_text, g.user.key, parent_id)
        else:
            flash('Comment cannot be blank.', category='error')

    return redirect(url_for('post.view_post', post_id=post_id))


@mod.route('/_vote/<int:post_id>', methods=['POST'])
def vote(post_id):

    post = Post.get_by_id(post_id)
    past_voters = map(lambda x: x.voter_id, post.voters)
    author = post.author.get()
    direction = request.form['direction']

    if g.user.key in past_voters:
        #if user has voted, update his direction
        previous_vote = post.voters[past_voters.index(g.user.key)]
        previous_vote.direction = direction
    else:
        #else create new voter
        new_voter = Voter(voter_id=g.user.key, direction=direction)
        post.voters.append(new_voter)

    post.votes += int(direction)
    author.karma += int(direction)

    post.put()
    author.put()

    return jsonify(result='ok')


@mod.route('/', methods=['GET', 'POST'])
@login_required
def view_or_submit():

    if request.method == "POST":
        if not all(v for k, v in request.form.items() if k != 'description'):
            flash('Submission must have a title and link', category='error')
            return redirect(url_for('frontend.index'))

        title = request.form['title']
        link = request.form['link']
        desc = request.form['description']
        user = g.user

        p = Post()
        p.add(title, link, desc, user.key)
        flash('Post submitted successfully!', category='success')

    return redirect(url_for('frontend.index'))

app/templates/base.html
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title> {% block title %} {% endblock %} </title>
  <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap-responsive.min.css') }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='bootstrap.min.css') }}">
  <link rel="stylesheet" href="{{ url_for('static', filename='style.css') }}">
  <link href='http://fonts.googleapis.com/css?family=Dancing+Script' rel='stylesheet' type='text/css'>
  <link href='http://fonts.googleapis.com/css?family=Josefin+Sans' rel='stylesheet' type='text/css'>
  <style> {% block css %} {% endblock %} </style>
</head>
<body>
{% include 'navbar.html' %}
{% with messages = get_flashed_messages(with_categories=True) %}
  {% if messages %}
            {% for category, message in messages %}
            <div class="alert alert-{{ category }}">
                <button type="button" class="close" data-dismiss="alert">×</button>
                {{ message }}
            </div>
            {% endfor %}
    {% endif %}
{% endwith %}
{% block body %}
{% endblock %}
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.8.1/jquery.min.js"></script>
<script src="{{ url_for('static', filename='js/bootstrap.min.js') }}"></script>
<script type=text/javascript>
  $SCRIPT_ROOT = {{ request.script_root|tojson|safe }};
</script>
<script src="{{ url_for('static', filename='js/navigate_vote.js') }}"></script>
{% block js %}
{% endblock %}
</body>
</html>

app/templates/comment.html
{% extends "base.html" %}

{% block body %}
{% from "macros/_render_comments.html" import render_comments with context %}

{{ render_comments(comments) }}

{% endblock %}

{% block js %}
<script src="{{ url_for('static', filename='js/comment_reply.js') }}"></script>
{% endblock %}

app/templates/index.html
{% extends "base.html" %}

{% block title %} FlaskrNews {% endblock %}
{% block body %}
{% from "macros/_render_post.html" import render_post with context %}
<div class="link_wrapper">
    {% for post, votes in content %}
        {{ render_post(post, loop.index, votes, page_number, last=loop.last) }}
    {% endfor %}
</div>

{% endblock %}


{% block js %}
<script src="{{ url_for('static', filename='js/scroll_load.js') }}"></script>
<script>
$(function () { $("html, body").animate({ scrollTop: 0 }, 600); })
</script>
{% endblock %}

app/templates/login.html
{% block title %} Login {% endblock %}
{% extends "base.html" %}

{% block body %}

<div class="form-container">
    <h1> Sign In </h1>
    {% if error %}
    <div class="alert alert-error">
        <button type="button" class="close" data-dismiss="alert">×</button>
        Invalid Credentials!
    </div>
    {% endif %}
    <form class="form-horizontal" method="POST" action='{{'/login?after=' + next_url}}'>
        <div class="control-group">
            <label class="control-label" for="inputUsername">Username</label>
            <div class="controls">
                <input name="username" type="text" id="inputUsername" placeholder="UserName">
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="inputPassword">Password</label>
            <div class="controls">
                <input name="password" type="password" id="inputPassword" placeholder="Password">
            </div>
        </div>
        <div class="control-group">
            <div class="controls">
                <label class="checkbox">
                    <input type="checkbox"> Remember me
                </label>
                <button type="submit" class="btn">Sign in</button>
                <a id="register" class="btn" href="#" style="margin-left: 70px">Register</a>
            </div>
        </div>
    </form>
</div>

{% endblock %}

{% block js %}
<script src="{{ url_for('static', filename='js/validate.js') }}"></script>
{% endblock %}

app/templates/navbar.html
<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <a class="brand" href="/">FlaskrNews</a>
        <ul class="nav">
            <li class="divider-vertical"></li>
            <li class="active"><a href="#">Hot</a></li>
            <li class="divider-vertical"></li>
            <li><a href="#">New</a></li>
            <li class="divider-vertical"></li>
            <li><a href="#submitModal" role="button" data-toggle="modal">Submit</a></li>
            <div class="modal hide fade in" id="submitModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="false">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                <div class="modal-body">
                    {% include 'submit.html' %}
                </div>
            </div>
        </ul>
        <form class="navbar-search">
            <input type="text" class="search-query" placeholder="Search" style="font-family: 'Josefin Sans'">
        </form>
        {% if session.get('username') is none %}
        <ul class="nav pull-right">
            <li><a href="{{ url_for('account.login') }}">Login</a></li>
        </ul>
        {% else %}
        <ul class="nav pull-right">
            <li class="divider-vertical"></li>
            <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">{{ session.username }}({{ g.user.karma }})<b class="caret"></b></a>
                <ul class="dropdown-menu">
                    <li><a href="#">Preferences</a></li>
                    <li><a href="#">Profile</a></li>
                    <li class="divider"></li>
                    <li><a href="{{ url_for('account.logout') }}">LogOut</a></li>
                </ul>
            </li>
        </ul>
        {% endif %}
    </div>
</div>

app/templates/post.html
{% set post,votes = content %}
{% block title %} {{ post.title }} {% endblock %}
{% extends "base.html" %}

{% block body %}
{% from "macros/_render_post.html" import render_post with context %}

<div class="link_wrapper">
    {{ render_post(post=post,voters=votes,comments=comments) }}
</div>


{% endblock %}

{% block js %}
<script src="{{ url_for('static', filename='js/comment_reply.js') }}"></script>
<script src="{{ url_for('static', filename='js/comment_collapse.js') }}"></script>
{% endblock %}

app/templates/register.html
<h1> Register </h1>
<form class="form-horizontal" method="POST" action='/register'>
      <div class="control-group">
          <label class="control-label" for="inputUsername">Username</label>
          <div class="controls">
              <input name="username" type="text" id="inputUsername" placeholder="UserName">
          </div>
      </div>
      <div class="control-group">
          <label class="control-label" for="inputPassword">Password</label>
          <div class="controls">
              <input name="password" type="password" id="inputPassword" placeholder="Password">
          </div>
     </div>
     <div class="control-group">
          <label class="control-label" for="inputConfirm">Confirm Password</label>
          <div class="controls">
              <input type="password" id="inputConfirm" placeholder="Confirm Password">
          </div>
     </div>
     <div class="control-group">
         <div class="controls">
             <button type="submit" class="btn">Register</button>
         </div>
      </div>
</form>

app/templates/submit.html
<div>
    <form class="form-horizontal" method="POST" action='/post/'>
        <h1> Submit </h1>
        <div class="control-group">
            <label class="control-label" for="inputTitle">Title</label>
            <div class="controls">
                <input name="title" type="text" id="inputTitle" placeholder="Title">
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="inputLink">Link</label>
            <div class="controls">
                <input name="link" type="text" id="inputLink" placeholder="Link">
            </div>
        </div>
        <div class="control-group">
            <label class="control-label" for="inputDescription">Description</label>
            <div class="controls">
                <textarea name="description" id="inputDescription" rows="5" placeholder="Add some details"></textarea>
            </div>
        </div>
        <div class="control-group">
            <div class="controls">
                <button type="submit" class="btn">Submit</button>
            </div>
        </div>
    </form>
</div>